version: "3"
services:
  mongo:
    image: mongo
    container_name: qtb_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - data:/data/db
    env_file:
      - .env
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - prod_network

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    restart: always
    container_name: qtb_api
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - prod_network
    profiles: ['prod']
    depends_on:
      - mongo

  admin:
    build:
      context: .
      dockerfile: admin.dockerfile
    container_name: qtb_admin
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - prod_network
    profiles: ['prod']
    depends_on:
      - api

volumes:
  data:

networks:
  prod_network:
    driver: bridge