version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/opt/db
    env_file:
      - .env
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - myNetwork

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    restart: always
    container_name: api
    env_file:
      - .env
    ports:
      - 3002:3000
    networks:
      - myNetwork
    depends_on:
      - mongo

  admin:
    build:
      context: .
      dockerfile: admin.dockerfile
    container_name: admin
    restart: always
    depends_on:
      - api
    volumes:
      - .env
    ports:
      - 8080:8080
    networks:
      - myNetwork

  client:
    build:
      context: .
      dockerfile: client.dockerfile
    restart: always
    container_name: client
    volumes:
      - .env
    ports:
      - 3000:3000
    networks:
      - myNetwork
    depends_on:
      - api

networks:
  myNetwork:
    driver: bridge