version: '3'
services:
  front:
    build:
      context: .
      dockerfile: front.dockerfile
    container_name: front
    restart: always
    ports:
      - "80:8080"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - ../.env
    command: --wiredTigerCacheSizeGB 1.5
